name: Create Azure Resources

on:
  workflow_dispatch:
  push:
    paths:
      - 'bicep/**/*.bicep'

jobs:
  create-azure-resources:

    env:      
      LOCATION: 'canadacentral'
      RG_NAME: 'rg-apim-vault-demo'

    runs-on: ubuntu-latest

    steps:
      
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: deploy
        id: createResources
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
          scope: subscription
          region: ${{ env.LOCATION }}        
          template: ./bicep/main.bicep
          parameters: location=${{ env.LOCATION }} resourceGroupName=${{ env.RG_NAME }} administratorEmail=${{ secrets.PUBLISHER_EMAIL }} organizationName=${{ secrets.PUBLISHER_NAME }}
                    